apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "0702testingapp-1"
  description: "0702testingapp-1"

  links:
    - url: https://github.com/RohanAwasthi/0702testingapp-1
      title: "0702testingapp-1"
      icon: code

  labels:
    system: web-apps
    trackid: "0702testingapp-1"
    environmentname: my-python-env-testing-1

  tags:
    - python
    - aws
    - "applicationtype-webapplication"

  annotations:
    # add elastic beanstalk annotation
    jenkins.io/github-folder: 'custom-actions/tf-0702testingapp-1'
    github.com/project-slug: RohanAwasthi/0702testingapp-1
    backstage.io/techdocs-ref: dir:.
    backstage.io/linguist: https://github.com/ItRachii/ebs-sample-python-application
    sonarqube.org/project-key: 'python-app/aws-elb-python'

spec:
  type: service
  lifecycle: experimental
  system: elasticbeanstalk
  owner: "neelesh.shekhar"
